apiVersion: v1
kind: Service
metadata:
  name: qa-agent-distributor
spec:
  type: ClusterIP
  selector:
    app: qa-agent-distributor
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
